export const colors = [
{name: 'black', hexcode: '#000000', degrees: '', categories: ['greyscale'],},
{name: 'slate',  hexcode: '#404040', degrees: '', categories: ['greyscale'],},
{name: 'grey',  hexcode: '#808080', degrees: '', categories: ['greyscale'],},
{name: 'silver',  hexcode: '#C0C0C0', degrees: '', categories: ['greyscale'],},
{name: 'white',  hexcode: '#ffffff', degrees: '', categories: ['greyscale'],},

{name: 'brown',  hexcode: '#88540B', degrees: '', categories: ['brownscale'],},
{name: 'auburn',  hexcode: '#A52A2A', degrees: '', categories: ['brownscale'],},
{name: 'taupe',  hexcode: '#a9a48e', degrees: '', categories: ['brownscale'],},
{name: 'beige',  hexcode: '#F5F5DC', degrees: '', categories: ['brownscale'],},
{name: 'umber',  hexcode: '#8B4513', degrees: '', categories: ['brownscale'],},
{name: 'sienna',  hexcode: '#A0522D', degrees: '', categories: ['brownscale'],},
{name: 'sepia',  hexcode: '#5E2612', degrees: '', categories: ['brownscale'],},

{name: 'red',  hexcode: '#FF0000', degrees: '0', categories: ['primary'],},
{name: 'yellow',  hexcode: '#FFFF00', degrees: '60', categories: ['primary'],},
{name: 'green',  hexcode: '#00FF00', degrees: '120', categories: ['primary'],},
{name: 'cyan',  hexcode: '#00FFFF', degrees: '180', categories: ['primary'],},
{name: 'blue',  hexcode: '#0000FF', degrees: '240', categories: ['primary'],},
{name: 'magenta',  hexcode: '#FF00FF', degrees: '300', categories: ['primary'],},

{name: 'orange',  hexcode: '#FF8000', degrees: '30', categories: ['secondary'],},
{name: 'chartreuse',  hexcode: '#80FF00', degrees: '90', categories: ['secondary'],},
{name: 'spring',  hexcode: '#00FF80', degrees: '150', categories: ['secondary'],},
{name: 'azure',  hexcode: '#0080FF', degrees: '210', categories: ['secondary'],},
{name: 'violet',  hexcode: '#8000FF', degrees: '270', categories: ['secondary'],},
{name: 'rose',  hexcode: '#FF0080', degrees: '330', categories: ['secondary'],},

{name: 'vermilion',  hexcode: '#FF4400', degrees: '15', categories: ['tertiary'],},
{name: 'amber',  hexcode: '#FFC300', degrees: '45', categories: ['tertiary'],},
{name: 'lime',  hexcode: '#C3FF00', degrees: '75', categories: ['tertiary'],},
{name: 'harlequin',  hexcode: '#44FF00', degrees: '105', categories: ['tertiary'],},
{name: 'erin',  hexcode: '#00FF44', degrees: '135', categories: ['tertiary'],},
{name: 'aquamarine',  hexcode: '#00FFC3', degrees: '165', categories: ['tertiary'],},
{name: 'capri',  hexcode: '#00C3FF', degrees: '195', categories: ['tertiary'],},
{name: 'cerulean',  hexcode: '#0044FF', degrees: '225', categories: ['tertiary'],},
{name: 'periwinkle',  hexcode: '#4400FF', degrees: '255', categories: ['tertiary'],},
{name: 'purple',  hexcode: '#C300FF', degrees: '285', categories: ['tertiary'],},
{name: 'cerise',  hexcode: '#FF00C3', degrees: '315', categories: ['tertiary'],},
{name: 'crimson',  hexcode: '#FF0044', degrees: '345', categories: ['tertiary'],},

{name: 'scarlet',  hexcode: '#FF2000', degrees: '7.5', categories: ['quaternary'],},
{name: 'persimmon',  hexcode: '#FF6000', degrees: '22.5', categories: ['quaternary'],},
{name: 'orange-peel',  hexcode: '#FFA000', degrees: '37.5', categories: ['quaternary'],},
{name: 'golden-yellow',  hexcode: '#FFE000', degrees: '52.5', categories: ['quaternary'],},
{name: 'lemon',  hexcode: '#E0FF00', degrees: '67.5', categories: ['quaternary'],},
{name: 'spring-bud',  hexcode: '#A0FF00', degrees: '82.5', categories: ['quaternary'],},
{name: 'bright-green',  hexcode: '#60FF00', degrees: '97.5', categories: ['quaternary'],},
{name: 'neon',  hexcode: '#20FF00', degrees: '112.5', categories: ['quaternary'],},
{name: 'jade',  hexcode: '#00FF20', degrees: '127.5', categories: ['quaternary'],},
{name: 'emerald',  hexcode: '#00FF60', degrees: '142.5', categories: ['quaternary'],},
{name: 'mint',  hexcode: '#00FFA0', degrees: '157.5', categories: ['quaternary'],},
{name: 'turquoise',  hexcode: '#00FFE0', degrees: '172.5', categories: ['quaternary'],},
{name: 'sky',  hexcode: '#00E0FF', degrees: '187.5', categories: ['quaternary'],},
{name: 'cornflower',  hexcode: '#00A0FF', degrees: '202.5', categories: ['quaternary'],},
{name: 'cobalt',  hexcode: '#0060FF', degrees: '217.5', categories: ['quaternary'],},
{name: 'sapphire',  hexcode: '#0020FF', degrees: '232.5', categories: ['quaternary'],},
{name: 'iris',  hexcode: '#2000FF', degrees: '247.5', categories: ['quaternary'],},
{name: 'veronica',  hexcode: '#8000FF', degrees: '262.5', categories: ['quaternary'],},
{name: 'amethyst',  hexcode: '#A000FF', degrees: '277.5', categories: ['quaternary'],},
{name: 'phlox',  hexcode: '#E000FF', degrees: '292.5', categories: ['quaternary'],},
{name: 'fuchsia',  hexcode: '#FF00E0', degrees: '307.5', categories: ['quaternary'],},
{name: 'deep-pink',  hexcode: '#FF00A0', degrees: '322.5', categories: ['quaternary'],},
{name: 'raspberry',  hexcode: '#FF0060', degrees: '337.5', categories: ['quaternary'],},
{name: 'amaranth',  hexcode: '#FF0020', degrees: '352.5', categories: ['quaternary'],},
];

